{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "spacelift-worker.fullname" . }}-vpa
  labels:
    {{- include "spacelift-worker.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "spacelift-worker.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.mode |quote }}

  {{- if .Values.vpa.enabled }}
  resourcePolicy:
    containerPolicies:
      - containerName: dind
        minAllowed:
          cpu: {{ .Values.vpa.bounds.min.cpu | quote }}
          memory: {{ .Values.vpa.bounds.min.memory | quote}}
        maxAllowed:
          cpu: {{ .Values.vpa.bounds.max.cpu | quote }}
          memory: {{ .Values.vpa.bounds.max.memory | quote }}
      - containerName: launcher
        mode: Off
  {{- end }}
  {{- end }}
